/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.beligum.blocks.schema.ebucore.v2015.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class alternativeDateType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"alternativeDateType\",\"namespace\":\"com.beligum.blocks.schema.ebucore.v2015.avro\",\"fields\":[{\"name\":\"startYear\",\"type\":[\"null\",\"string\"],\"source\":\"attribute startYear\"},{\"name\":\"startDate\",\"type\":[\"null\",\"string\"],\"source\":\"attribute startDate\"},{\"name\":\"startTime\",\"type\":[\"null\",\"string\"],\"source\":\"attribute startTime\"},{\"name\":\"endYear\",\"type\":[\"null\",\"string\"],\"source\":\"attribute endYear\"},{\"name\":\"endDate\",\"type\":[\"null\",\"string\"],\"source\":\"attribute endDate\"},{\"name\":\"endTime\",\"type\":[\"null\",\"string\"],\"source\":\"attribute endTime\"},{\"name\":\"period\",\"type\":[\"null\",\"string\"],\"source\":\"attribute period\"},{\"name\":\"typeLabel\",\"type\":[\"null\",\"string\"],\"source\":\"attribute typeLabel\"},{\"name\":\"typeDefinition\",\"type\":[\"null\",\"string\"],\"source\":\"attribute typeDefinition\"},{\"name\":\"typeLink\",\"type\":[\"null\",\"string\"],\"source\":\"attribute typeLink\"},{\"name\":\"typeSource\",\"type\":[\"null\",\"string\"],\"source\":\"attribute typeSource\"},{\"name\":\"typeNamespace\",\"type\":[\"null\",\"string\"],\"source\":\"attribute typeNamespace\"},{\"name\":\"typeLanguage\",\"type\":[\"null\",\"string\"],\"source\":\"attribute typeLanguage\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence startYear;
  @Deprecated public java.lang.CharSequence startDate;
  @Deprecated public java.lang.CharSequence startTime;
  @Deprecated public java.lang.CharSequence endYear;
  @Deprecated public java.lang.CharSequence endDate;
  @Deprecated public java.lang.CharSequence endTime;
  @Deprecated public java.lang.CharSequence period;
  @Deprecated public java.lang.CharSequence typeLabel;
  @Deprecated public java.lang.CharSequence typeDefinition;
  @Deprecated public java.lang.CharSequence typeLink;
  @Deprecated public java.lang.CharSequence typeSource;
  @Deprecated public java.lang.CharSequence typeNamespace;
  @Deprecated public java.lang.CharSequence typeLanguage;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public alternativeDateType() {}

  /**
   * All-args constructor.
   */
  public alternativeDateType(java.lang.CharSequence startYear, java.lang.CharSequence startDate, java.lang.CharSequence startTime, java.lang.CharSequence endYear, java.lang.CharSequence endDate, java.lang.CharSequence endTime, java.lang.CharSequence period, java.lang.CharSequence typeLabel, java.lang.CharSequence typeDefinition, java.lang.CharSequence typeLink, java.lang.CharSequence typeSource, java.lang.CharSequence typeNamespace, java.lang.CharSequence typeLanguage) {
    this.startYear = startYear;
    this.startDate = startDate;
    this.startTime = startTime;
    this.endYear = endYear;
    this.endDate = endDate;
    this.endTime = endTime;
    this.period = period;
    this.typeLabel = typeLabel;
    this.typeDefinition = typeDefinition;
    this.typeLink = typeLink;
    this.typeSource = typeSource;
    this.typeNamespace = typeNamespace;
    this.typeLanguage = typeLanguage;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return startYear;
    case 1: return startDate;
    case 2: return startTime;
    case 3: return endYear;
    case 4: return endDate;
    case 5: return endTime;
    case 6: return period;
    case 7: return typeLabel;
    case 8: return typeDefinition;
    case 9: return typeLink;
    case 10: return typeSource;
    case 11: return typeNamespace;
    case 12: return typeLanguage;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: startYear = (java.lang.CharSequence)value$; break;
    case 1: startDate = (java.lang.CharSequence)value$; break;
    case 2: startTime = (java.lang.CharSequence)value$; break;
    case 3: endYear = (java.lang.CharSequence)value$; break;
    case 4: endDate = (java.lang.CharSequence)value$; break;
    case 5: endTime = (java.lang.CharSequence)value$; break;
    case 6: period = (java.lang.CharSequence)value$; break;
    case 7: typeLabel = (java.lang.CharSequence)value$; break;
    case 8: typeDefinition = (java.lang.CharSequence)value$; break;
    case 9: typeLink = (java.lang.CharSequence)value$; break;
    case 10: typeSource = (java.lang.CharSequence)value$; break;
    case 11: typeNamespace = (java.lang.CharSequence)value$; break;
    case 12: typeLanguage = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'startYear' field.
   */
  public java.lang.CharSequence getStartYear() {
    return startYear;
  }

  /**
   * Sets the value of the 'startYear' field.
   * @param value the value to set.
   */
  public void setStartYear(java.lang.CharSequence value) {
    this.startYear = value;
  }

  /**
   * Gets the value of the 'startDate' field.
   */
  public java.lang.CharSequence getStartDate() {
    return startDate;
  }

  /**
   * Sets the value of the 'startDate' field.
   * @param value the value to set.
   */
  public void setStartDate(java.lang.CharSequence value) {
    this.startDate = value;
  }

  /**
   * Gets the value of the 'startTime' field.
   */
  public java.lang.CharSequence getStartTime() {
    return startTime;
  }

  /**
   * Sets the value of the 'startTime' field.
   * @param value the value to set.
   */
  public void setStartTime(java.lang.CharSequence value) {
    this.startTime = value;
  }

  /**
   * Gets the value of the 'endYear' field.
   */
  public java.lang.CharSequence getEndYear() {
    return endYear;
  }

  /**
   * Sets the value of the 'endYear' field.
   * @param value the value to set.
   */
  public void setEndYear(java.lang.CharSequence value) {
    this.endYear = value;
  }

  /**
   * Gets the value of the 'endDate' field.
   */
  public java.lang.CharSequence getEndDate() {
    return endDate;
  }

  /**
   * Sets the value of the 'endDate' field.
   * @param value the value to set.
   */
  public void setEndDate(java.lang.CharSequence value) {
    this.endDate = value;
  }

  /**
   * Gets the value of the 'endTime' field.
   */
  public java.lang.CharSequence getEndTime() {
    return endTime;
  }

  /**
   * Sets the value of the 'endTime' field.
   * @param value the value to set.
   */
  public void setEndTime(java.lang.CharSequence value) {
    this.endTime = value;
  }

  /**
   * Gets the value of the 'period' field.
   */
  public java.lang.CharSequence getPeriod() {
    return period;
  }

  /**
   * Sets the value of the 'period' field.
   * @param value the value to set.
   */
  public void setPeriod(java.lang.CharSequence value) {
    this.period = value;
  }

  /**
   * Gets the value of the 'typeLabel' field.
   */
  public java.lang.CharSequence getTypeLabel() {
    return typeLabel;
  }

  /**
   * Sets the value of the 'typeLabel' field.
   * @param value the value to set.
   */
  public void setTypeLabel(java.lang.CharSequence value) {
    this.typeLabel = value;
  }

  /**
   * Gets the value of the 'typeDefinition' field.
   */
  public java.lang.CharSequence getTypeDefinition() {
    return typeDefinition;
  }

  /**
   * Sets the value of the 'typeDefinition' field.
   * @param value the value to set.
   */
  public void setTypeDefinition(java.lang.CharSequence value) {
    this.typeDefinition = value;
  }

  /**
   * Gets the value of the 'typeLink' field.
   */
  public java.lang.CharSequence getTypeLink() {
    return typeLink;
  }

  /**
   * Sets the value of the 'typeLink' field.
   * @param value the value to set.
   */
  public void setTypeLink(java.lang.CharSequence value) {
    this.typeLink = value;
  }

  /**
   * Gets the value of the 'typeSource' field.
   */
  public java.lang.CharSequence getTypeSource() {
    return typeSource;
  }

  /**
   * Sets the value of the 'typeSource' field.
   * @param value the value to set.
   */
  public void setTypeSource(java.lang.CharSequence value) {
    this.typeSource = value;
  }

  /**
   * Gets the value of the 'typeNamespace' field.
   */
  public java.lang.CharSequence getTypeNamespace() {
    return typeNamespace;
  }

  /**
   * Sets the value of the 'typeNamespace' field.
   * @param value the value to set.
   */
  public void setTypeNamespace(java.lang.CharSequence value) {
    this.typeNamespace = value;
  }

  /**
   * Gets the value of the 'typeLanguage' field.
   */
  public java.lang.CharSequence getTypeLanguage() {
    return typeLanguage;
  }

  /**
   * Sets the value of the 'typeLanguage' field.
   * @param value the value to set.
   */
  public void setTypeLanguage(java.lang.CharSequence value) {
    this.typeLanguage = value;
  }

  /** Creates a new alternativeDateType RecordBuilder */
  public static com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder newBuilder() {
    return new com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder();
  }
  
  /** Creates a new alternativeDateType RecordBuilder by copying an existing Builder */
  public static com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder newBuilder(com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder other) {
    return new com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder(other);
  }
  
  /** Creates a new alternativeDateType RecordBuilder by copying an existing alternativeDateType instance */
  public static com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder newBuilder(com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType other) {
    return new com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder(other);
  }
  
  /**
   * RecordBuilder for alternativeDateType instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<alternativeDateType>
    implements org.apache.avro.data.RecordBuilder<alternativeDateType> {

    private java.lang.CharSequence startYear;
    private java.lang.CharSequence startDate;
    private java.lang.CharSequence startTime;
    private java.lang.CharSequence endYear;
    private java.lang.CharSequence endDate;
    private java.lang.CharSequence endTime;
    private java.lang.CharSequence period;
    private java.lang.CharSequence typeLabel;
    private java.lang.CharSequence typeDefinition;
    private java.lang.CharSequence typeLink;
    private java.lang.CharSequence typeSource;
    private java.lang.CharSequence typeNamespace;
    private java.lang.CharSequence typeLanguage;

    /** Creates a new Builder */
    private Builder() {
      super(com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.startYear)) {
        this.startYear = data().deepCopy(fields()[0].schema(), other.startYear);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.startDate)) {
        this.startDate = data().deepCopy(fields()[1].schema(), other.startDate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.startTime)) {
        this.startTime = data().deepCopy(fields()[2].schema(), other.startTime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.endYear)) {
        this.endYear = data().deepCopy(fields()[3].schema(), other.endYear);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.endDate)) {
        this.endDate = data().deepCopy(fields()[4].schema(), other.endDate);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.endTime)) {
        this.endTime = data().deepCopy(fields()[5].schema(), other.endTime);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.period)) {
        this.period = data().deepCopy(fields()[6].schema(), other.period);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.typeLabel)) {
        this.typeLabel = data().deepCopy(fields()[7].schema(), other.typeLabel);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.typeDefinition)) {
        this.typeDefinition = data().deepCopy(fields()[8].schema(), other.typeDefinition);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.typeLink)) {
        this.typeLink = data().deepCopy(fields()[9].schema(), other.typeLink);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.typeSource)) {
        this.typeSource = data().deepCopy(fields()[10].schema(), other.typeSource);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.typeNamespace)) {
        this.typeNamespace = data().deepCopy(fields()[11].schema(), other.typeNamespace);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.typeLanguage)) {
        this.typeLanguage = data().deepCopy(fields()[12].schema(), other.typeLanguage);
        fieldSetFlags()[12] = true;
      }
    }
    
    /** Creates a Builder by copying an existing alternativeDateType instance */
    private Builder(com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType other) {
            super(com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.SCHEMA$);
      if (isValidValue(fields()[0], other.startYear)) {
        this.startYear = data().deepCopy(fields()[0].schema(), other.startYear);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.startDate)) {
        this.startDate = data().deepCopy(fields()[1].schema(), other.startDate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.startTime)) {
        this.startTime = data().deepCopy(fields()[2].schema(), other.startTime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.endYear)) {
        this.endYear = data().deepCopy(fields()[3].schema(), other.endYear);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.endDate)) {
        this.endDate = data().deepCopy(fields()[4].schema(), other.endDate);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.endTime)) {
        this.endTime = data().deepCopy(fields()[5].schema(), other.endTime);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.period)) {
        this.period = data().deepCopy(fields()[6].schema(), other.period);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.typeLabel)) {
        this.typeLabel = data().deepCopy(fields()[7].schema(), other.typeLabel);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.typeDefinition)) {
        this.typeDefinition = data().deepCopy(fields()[8].schema(), other.typeDefinition);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.typeLink)) {
        this.typeLink = data().deepCopy(fields()[9].schema(), other.typeLink);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.typeSource)) {
        this.typeSource = data().deepCopy(fields()[10].schema(), other.typeSource);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.typeNamespace)) {
        this.typeNamespace = data().deepCopy(fields()[11].schema(), other.typeNamespace);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.typeLanguage)) {
        this.typeLanguage = data().deepCopy(fields()[12].schema(), other.typeLanguage);
        fieldSetFlags()[12] = true;
      }
    }

    /** Gets the value of the 'startYear' field */
    public java.lang.CharSequence getStartYear() {
      return startYear;
    }
    
    /** Sets the value of the 'startYear' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder setStartYear(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.startYear = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'startYear' field has been set */
    public boolean hasStartYear() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'startYear' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder clearStartYear() {
      startYear = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'startDate' field */
    public java.lang.CharSequence getStartDate() {
      return startDate;
    }
    
    /** Sets the value of the 'startDate' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder setStartDate(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.startDate = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'startDate' field has been set */
    public boolean hasStartDate() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'startDate' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder clearStartDate() {
      startDate = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'startTime' field */
    public java.lang.CharSequence getStartTime() {
      return startTime;
    }
    
    /** Sets the value of the 'startTime' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder setStartTime(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.startTime = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'startTime' field has been set */
    public boolean hasStartTime() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'startTime' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder clearStartTime() {
      startTime = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'endYear' field */
    public java.lang.CharSequence getEndYear() {
      return endYear;
    }
    
    /** Sets the value of the 'endYear' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder setEndYear(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.endYear = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'endYear' field has been set */
    public boolean hasEndYear() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'endYear' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder clearEndYear() {
      endYear = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'endDate' field */
    public java.lang.CharSequence getEndDate() {
      return endDate;
    }
    
    /** Sets the value of the 'endDate' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder setEndDate(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.endDate = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'endDate' field has been set */
    public boolean hasEndDate() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'endDate' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder clearEndDate() {
      endDate = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'endTime' field */
    public java.lang.CharSequence getEndTime() {
      return endTime;
    }
    
    /** Sets the value of the 'endTime' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder setEndTime(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.endTime = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'endTime' field has been set */
    public boolean hasEndTime() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'endTime' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder clearEndTime() {
      endTime = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'period' field */
    public java.lang.CharSequence getPeriod() {
      return period;
    }
    
    /** Sets the value of the 'period' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder setPeriod(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.period = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'period' field has been set */
    public boolean hasPeriod() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'period' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder clearPeriod() {
      period = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'typeLabel' field */
    public java.lang.CharSequence getTypeLabel() {
      return typeLabel;
    }
    
    /** Sets the value of the 'typeLabel' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder setTypeLabel(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.typeLabel = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'typeLabel' field has been set */
    public boolean hasTypeLabel() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'typeLabel' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder clearTypeLabel() {
      typeLabel = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'typeDefinition' field */
    public java.lang.CharSequence getTypeDefinition() {
      return typeDefinition;
    }
    
    /** Sets the value of the 'typeDefinition' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder setTypeDefinition(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.typeDefinition = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'typeDefinition' field has been set */
    public boolean hasTypeDefinition() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'typeDefinition' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder clearTypeDefinition() {
      typeDefinition = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'typeLink' field */
    public java.lang.CharSequence getTypeLink() {
      return typeLink;
    }
    
    /** Sets the value of the 'typeLink' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder setTypeLink(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.typeLink = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'typeLink' field has been set */
    public boolean hasTypeLink() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'typeLink' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder clearTypeLink() {
      typeLink = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'typeSource' field */
    public java.lang.CharSequence getTypeSource() {
      return typeSource;
    }
    
    /** Sets the value of the 'typeSource' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder setTypeSource(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.typeSource = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'typeSource' field has been set */
    public boolean hasTypeSource() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'typeSource' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder clearTypeSource() {
      typeSource = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'typeNamespace' field */
    public java.lang.CharSequence getTypeNamespace() {
      return typeNamespace;
    }
    
    /** Sets the value of the 'typeNamespace' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder setTypeNamespace(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.typeNamespace = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'typeNamespace' field has been set */
    public boolean hasTypeNamespace() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'typeNamespace' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder clearTypeNamespace() {
      typeNamespace = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'typeLanguage' field */
    public java.lang.CharSequence getTypeLanguage() {
      return typeLanguage;
    }
    
    /** Sets the value of the 'typeLanguage' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder setTypeLanguage(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.typeLanguage = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'typeLanguage' field has been set */
    public boolean hasTypeLanguage() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'typeLanguage' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.alternativeDateType.Builder clearTypeLanguage() {
      typeLanguage = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    public alternativeDateType build() {
      try {
        alternativeDateType record = new alternativeDateType();
        record.startYear = fieldSetFlags()[0] ? this.startYear : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.startDate = fieldSetFlags()[1] ? this.startDate : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.startTime = fieldSetFlags()[2] ? this.startTime : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.endYear = fieldSetFlags()[3] ? this.endYear : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.endDate = fieldSetFlags()[4] ? this.endDate : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.endTime = fieldSetFlags()[5] ? this.endTime : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.period = fieldSetFlags()[6] ? this.period : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.typeLabel = fieldSetFlags()[7] ? this.typeLabel : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.typeDefinition = fieldSetFlags()[8] ? this.typeDefinition : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.typeLink = fieldSetFlags()[9] ? this.typeLink : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.typeSource = fieldSetFlags()[10] ? this.typeSource : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.typeNamespace = fieldSetFlags()[11] ? this.typeNamespace : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.typeLanguage = fieldSetFlags()[12] ? this.typeLanguage : (java.lang.CharSequence) defaultValue(fields()[12]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
