/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.beligum.blocks.schema.ebucore.v2015.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class audioProgrammeReferenceScreenType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"audioProgrammeReferenceScreenType\",\"namespace\":\"com.beligum.blocks.schema.ebucore.v2015.avro\",\"fields\":[{\"name\":\"aspectRatio\",\"type\":[\"null\",\"float\"],\"source\":\"element aspectRatio\"},{\"name\":\"screenCentrePosition\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"screenCentrePositionType\",\"fields\":[{\"name\":\"azimuth\",\"type\":[\"null\",\"float\"],\"source\":\"attribute azimuth\"},{\"name\":\"elevation\",\"type\":[\"null\",\"float\"],\"source\":\"attribute elevation\"},{\"name\":\"distance\",\"type\":[\"null\",\"float\"],\"source\":\"attribute distance\"},{\"name\":\"X\",\"type\":[\"null\",\"float\"],\"source\":\"attribute X\"},{\"name\":\"Y\",\"type\":[\"null\",\"float\"],\"source\":\"attribute Y\"},{\"name\":\"Z\",\"type\":[\"null\",\"float\"],\"source\":\"attribute Z\"}]}],\"source\":\"element screenCentrePosition\"},{\"name\":\"screenWidth\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"screenWidthType\",\"fields\":[{\"name\":\"azimuth\",\"type\":[\"null\",\"float\"],\"source\":\"attribute azimuth\"},{\"name\":\"X\",\"type\":[\"null\",\"float\"],\"source\":\"attribute X\"}]}],\"source\":\"element screenWidth\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Float aspectRatio;
  @Deprecated public com.beligum.blocks.schema.ebucore.v2015.avro.screenCentrePositionType screenCentrePosition;
  @Deprecated public com.beligum.blocks.schema.ebucore.v2015.avro.screenWidthType screenWidth;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public audioProgrammeReferenceScreenType() {}

  /**
   * All-args constructor.
   */
  public audioProgrammeReferenceScreenType(java.lang.Float aspectRatio, com.beligum.blocks.schema.ebucore.v2015.avro.screenCentrePositionType screenCentrePosition, com.beligum.blocks.schema.ebucore.v2015.avro.screenWidthType screenWidth) {
    this.aspectRatio = aspectRatio;
    this.screenCentrePosition = screenCentrePosition;
    this.screenWidth = screenWidth;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return aspectRatio;
    case 1: return screenCentrePosition;
    case 2: return screenWidth;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: aspectRatio = (java.lang.Float)value$; break;
    case 1: screenCentrePosition = (com.beligum.blocks.schema.ebucore.v2015.avro.screenCentrePositionType)value$; break;
    case 2: screenWidth = (com.beligum.blocks.schema.ebucore.v2015.avro.screenWidthType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'aspectRatio' field.
   */
  public java.lang.Float getAspectRatio() {
    return aspectRatio;
  }

  /**
   * Sets the value of the 'aspectRatio' field.
   * @param value the value to set.
   */
  public void setAspectRatio(java.lang.Float value) {
    this.aspectRatio = value;
  }

  /**
   * Gets the value of the 'screenCentrePosition' field.
   */
  public com.beligum.blocks.schema.ebucore.v2015.avro.screenCentrePositionType getScreenCentrePosition() {
    return screenCentrePosition;
  }

  /**
   * Sets the value of the 'screenCentrePosition' field.
   * @param value the value to set.
   */
  public void setScreenCentrePosition(com.beligum.blocks.schema.ebucore.v2015.avro.screenCentrePositionType value) {
    this.screenCentrePosition = value;
  }

  /**
   * Gets the value of the 'screenWidth' field.
   */
  public com.beligum.blocks.schema.ebucore.v2015.avro.screenWidthType getScreenWidth() {
    return screenWidth;
  }

  /**
   * Sets the value of the 'screenWidth' field.
   * @param value the value to set.
   */
  public void setScreenWidth(com.beligum.blocks.schema.ebucore.v2015.avro.screenWidthType value) {
    this.screenWidth = value;
  }

  /** Creates a new audioProgrammeReferenceScreenType RecordBuilder */
  public static com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.Builder newBuilder() {
    return new com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.Builder();
  }
  
  /** Creates a new audioProgrammeReferenceScreenType RecordBuilder by copying an existing Builder */
  public static com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.Builder newBuilder(com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.Builder other) {
    return new com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.Builder(other);
  }
  
  /** Creates a new audioProgrammeReferenceScreenType RecordBuilder by copying an existing audioProgrammeReferenceScreenType instance */
  public static com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.Builder newBuilder(com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType other) {
    return new com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.Builder(other);
  }
  
  /**
   * RecordBuilder for audioProgrammeReferenceScreenType instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<audioProgrammeReferenceScreenType>
    implements org.apache.avro.data.RecordBuilder<audioProgrammeReferenceScreenType> {

    private java.lang.Float aspectRatio;
    private com.beligum.blocks.schema.ebucore.v2015.avro.screenCentrePositionType screenCentrePosition;
    private com.beligum.blocks.schema.ebucore.v2015.avro.screenWidthType screenWidth;

    /** Creates a new Builder */
    private Builder() {
      super(com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.aspectRatio)) {
        this.aspectRatio = data().deepCopy(fields()[0].schema(), other.aspectRatio);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.screenCentrePosition)) {
        this.screenCentrePosition = data().deepCopy(fields()[1].schema(), other.screenCentrePosition);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.screenWidth)) {
        this.screenWidth = data().deepCopy(fields()[2].schema(), other.screenWidth);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing audioProgrammeReferenceScreenType instance */
    private Builder(com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType other) {
            super(com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.SCHEMA$);
      if (isValidValue(fields()[0], other.aspectRatio)) {
        this.aspectRatio = data().deepCopy(fields()[0].schema(), other.aspectRatio);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.screenCentrePosition)) {
        this.screenCentrePosition = data().deepCopy(fields()[1].schema(), other.screenCentrePosition);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.screenWidth)) {
        this.screenWidth = data().deepCopy(fields()[2].schema(), other.screenWidth);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'aspectRatio' field */
    public java.lang.Float getAspectRatio() {
      return aspectRatio;
    }
    
    /** Sets the value of the 'aspectRatio' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.Builder setAspectRatio(java.lang.Float value) {
      validate(fields()[0], value);
      this.aspectRatio = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'aspectRatio' field has been set */
    public boolean hasAspectRatio() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'aspectRatio' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.Builder clearAspectRatio() {
      aspectRatio = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'screenCentrePosition' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.screenCentrePositionType getScreenCentrePosition() {
      return screenCentrePosition;
    }
    
    /** Sets the value of the 'screenCentrePosition' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.Builder setScreenCentrePosition(com.beligum.blocks.schema.ebucore.v2015.avro.screenCentrePositionType value) {
      validate(fields()[1], value);
      this.screenCentrePosition = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'screenCentrePosition' field has been set */
    public boolean hasScreenCentrePosition() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'screenCentrePosition' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.Builder clearScreenCentrePosition() {
      screenCentrePosition = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'screenWidth' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.screenWidthType getScreenWidth() {
      return screenWidth;
    }
    
    /** Sets the value of the 'screenWidth' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.Builder setScreenWidth(com.beligum.blocks.schema.ebucore.v2015.avro.screenWidthType value) {
      validate(fields()[2], value);
      this.screenWidth = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'screenWidth' field has been set */
    public boolean hasScreenWidth() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'screenWidth' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.audioProgrammeReferenceScreenType.Builder clearScreenWidth() {
      screenWidth = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public audioProgrammeReferenceScreenType build() {
      try {
        audioProgrammeReferenceScreenType record = new audioProgrammeReferenceScreenType();
        record.aspectRatio = fieldSetFlags()[0] ? this.aspectRatio : (java.lang.Float) defaultValue(fields()[0]);
        record.screenCentrePosition = fieldSetFlags()[1] ? this.screenCentrePosition : (com.beligum.blocks.schema.ebucore.v2015.avro.screenCentrePositionType) defaultValue(fields()[1]);
        record.screenWidth = fieldSetFlags()[2] ? this.screenWidth : (com.beligum.blocks.schema.ebucore.v2015.avro.screenWidthType) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
