/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.beligum.blocks.schema.ebucore.v2015.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class dimensionType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"dimensionType\",\"namespace\":\"com.beligum.blocks.schema.ebucore.v2015.avro\",\"fields\":[{\"name\":\"unit\",\"type\":[\"null\",\"string\"],\"source\":\"attribute unit\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence unit;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public dimensionType() {}

  /**
   * All-args constructor.
   */
  public dimensionType(java.lang.CharSequence unit) {
    this.unit = unit;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return unit;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: unit = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'unit' field.
   */
  public java.lang.CharSequence getUnit() {
    return unit;
  }

  /**
   * Sets the value of the 'unit' field.
   * @param value the value to set.
   */
  public void setUnit(java.lang.CharSequence value) {
    this.unit = value;
  }

  /** Creates a new dimensionType RecordBuilder */
  public static com.beligum.blocks.schema.ebucore.v2015.avro.dimensionType.Builder newBuilder() {
    return new com.beligum.blocks.schema.ebucore.v2015.avro.dimensionType.Builder();
  }
  
  /** Creates a new dimensionType RecordBuilder by copying an existing Builder */
  public static com.beligum.blocks.schema.ebucore.v2015.avro.dimensionType.Builder newBuilder(com.beligum.blocks.schema.ebucore.v2015.avro.dimensionType.Builder other) {
    return new com.beligum.blocks.schema.ebucore.v2015.avro.dimensionType.Builder(other);
  }
  
  /** Creates a new dimensionType RecordBuilder by copying an existing dimensionType instance */
  public static com.beligum.blocks.schema.ebucore.v2015.avro.dimensionType.Builder newBuilder(com.beligum.blocks.schema.ebucore.v2015.avro.dimensionType other) {
    return new com.beligum.blocks.schema.ebucore.v2015.avro.dimensionType.Builder(other);
  }
  
  /**
   * RecordBuilder for dimensionType instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<dimensionType>
    implements org.apache.avro.data.RecordBuilder<dimensionType> {

    private java.lang.CharSequence unit;

    /** Creates a new Builder */
    private Builder() {
      super(com.beligum.blocks.schema.ebucore.v2015.avro.dimensionType.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.beligum.blocks.schema.ebucore.v2015.avro.dimensionType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.unit)) {
        this.unit = data().deepCopy(fields()[0].schema(), other.unit);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing dimensionType instance */
    private Builder(com.beligum.blocks.schema.ebucore.v2015.avro.dimensionType other) {
            super(com.beligum.blocks.schema.ebucore.v2015.avro.dimensionType.SCHEMA$);
      if (isValidValue(fields()[0], other.unit)) {
        this.unit = data().deepCopy(fields()[0].schema(), other.unit);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'unit' field */
    public java.lang.CharSequence getUnit() {
      return unit;
    }
    
    /** Sets the value of the 'unit' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.dimensionType.Builder setUnit(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.unit = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'unit' field has been set */
    public boolean hasUnit() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'unit' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.dimensionType.Builder clearUnit() {
      unit = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public dimensionType build() {
      try {
        dimensionType record = new dimensionType();
        record.unit = fieldSetFlags()[0] ? this.unit : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
