/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.beligum.blocks.schema.ebucore.v2015.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class editUnitNumberType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"editUnitNumberType\",\"namespace\":\"com.beligum.blocks.schema.ebucore.v2015.avro\",\"fields\":[{\"name\":\"editRate\",\"type\":[\"null\",\"string\"],\"source\":\"attribute editRate\"},{\"name\":\"factorNumerator\",\"type\":[\"null\",\"string\"],\"source\":\"attribute factorNumerator\"},{\"name\":\"factorDenominator\",\"type\":[\"null\",\"string\"],\"source\":\"attribute factorDenominator\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence editRate;
  @Deprecated public java.lang.CharSequence factorNumerator;
  @Deprecated public java.lang.CharSequence factorDenominator;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public editUnitNumberType() {}

  /**
   * All-args constructor.
   */
  public editUnitNumberType(java.lang.CharSequence editRate, java.lang.CharSequence factorNumerator, java.lang.CharSequence factorDenominator) {
    this.editRate = editRate;
    this.factorNumerator = factorNumerator;
    this.factorDenominator = factorDenominator;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return editRate;
    case 1: return factorNumerator;
    case 2: return factorDenominator;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: editRate = (java.lang.CharSequence)value$; break;
    case 1: factorNumerator = (java.lang.CharSequence)value$; break;
    case 2: factorDenominator = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'editRate' field.
   */
  public java.lang.CharSequence getEditRate() {
    return editRate;
  }

  /**
   * Sets the value of the 'editRate' field.
   * @param value the value to set.
   */
  public void setEditRate(java.lang.CharSequence value) {
    this.editRate = value;
  }

  /**
   * Gets the value of the 'factorNumerator' field.
   */
  public java.lang.CharSequence getFactorNumerator() {
    return factorNumerator;
  }

  /**
   * Sets the value of the 'factorNumerator' field.
   * @param value the value to set.
   */
  public void setFactorNumerator(java.lang.CharSequence value) {
    this.factorNumerator = value;
  }

  /**
   * Gets the value of the 'factorDenominator' field.
   */
  public java.lang.CharSequence getFactorDenominator() {
    return factorDenominator;
  }

  /**
   * Sets the value of the 'factorDenominator' field.
   * @param value the value to set.
   */
  public void setFactorDenominator(java.lang.CharSequence value) {
    this.factorDenominator = value;
  }

  /** Creates a new editUnitNumberType RecordBuilder */
  public static com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.Builder newBuilder() {
    return new com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.Builder();
  }
  
  /** Creates a new editUnitNumberType RecordBuilder by copying an existing Builder */
  public static com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.Builder newBuilder(com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.Builder other) {
    return new com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.Builder(other);
  }
  
  /** Creates a new editUnitNumberType RecordBuilder by copying an existing editUnitNumberType instance */
  public static com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.Builder newBuilder(com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType other) {
    return new com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.Builder(other);
  }
  
  /**
   * RecordBuilder for editUnitNumberType instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<editUnitNumberType>
    implements org.apache.avro.data.RecordBuilder<editUnitNumberType> {

    private java.lang.CharSequence editRate;
    private java.lang.CharSequence factorNumerator;
    private java.lang.CharSequence factorDenominator;

    /** Creates a new Builder */
    private Builder() {
      super(com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.editRate)) {
        this.editRate = data().deepCopy(fields()[0].schema(), other.editRate);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.factorNumerator)) {
        this.factorNumerator = data().deepCopy(fields()[1].schema(), other.factorNumerator);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.factorDenominator)) {
        this.factorDenominator = data().deepCopy(fields()[2].schema(), other.factorDenominator);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing editUnitNumberType instance */
    private Builder(com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType other) {
            super(com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.SCHEMA$);
      if (isValidValue(fields()[0], other.editRate)) {
        this.editRate = data().deepCopy(fields()[0].schema(), other.editRate);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.factorNumerator)) {
        this.factorNumerator = data().deepCopy(fields()[1].schema(), other.factorNumerator);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.factorDenominator)) {
        this.factorDenominator = data().deepCopy(fields()[2].schema(), other.factorDenominator);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'editRate' field */
    public java.lang.CharSequence getEditRate() {
      return editRate;
    }
    
    /** Sets the value of the 'editRate' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.Builder setEditRate(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.editRate = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'editRate' field has been set */
    public boolean hasEditRate() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'editRate' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.Builder clearEditRate() {
      editRate = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'factorNumerator' field */
    public java.lang.CharSequence getFactorNumerator() {
      return factorNumerator;
    }
    
    /** Sets the value of the 'factorNumerator' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.Builder setFactorNumerator(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.factorNumerator = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'factorNumerator' field has been set */
    public boolean hasFactorNumerator() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'factorNumerator' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.Builder clearFactorNumerator() {
      factorNumerator = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'factorDenominator' field */
    public java.lang.CharSequence getFactorDenominator() {
      return factorDenominator;
    }
    
    /** Sets the value of the 'factorDenominator' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.Builder setFactorDenominator(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.factorDenominator = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'factorDenominator' field has been set */
    public boolean hasFactorDenominator() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'factorDenominator' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.editUnitNumberType.Builder clearFactorDenominator() {
      factorDenominator = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public editUnitNumberType build() {
      try {
        editUnitNumberType record = new editUnitNumberType();
        record.editRate = fieldSetFlags()[0] ? this.editRate : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.factorNumerator = fieldSetFlags()[1] ? this.factorNumerator : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.factorDenominator = fieldSetFlags()[2] ? this.factorDenominator : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
