/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.beligum.blocks.schema.ebucore.v2015.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class gainInteractionRangeType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"gainInteractionRangeType\",\"namespace\":\"com.beligum.blocks.schema.ebucore.v2015.avro\",\"fields\":[{\"name\":\"bound\",\"type\":[\"null\",\"string\"],\"source\":\"attribute bound\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence bound;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public gainInteractionRangeType() {}

  /**
   * All-args constructor.
   */
  public gainInteractionRangeType(java.lang.CharSequence bound) {
    this.bound = bound;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bound;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bound = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'bound' field.
   */
  public java.lang.CharSequence getBound() {
    return bound;
  }

  /**
   * Sets the value of the 'bound' field.
   * @param value the value to set.
   */
  public void setBound(java.lang.CharSequence value) {
    this.bound = value;
  }

  /** Creates a new gainInteractionRangeType RecordBuilder */
  public static com.beligum.blocks.schema.ebucore.v2015.avro.gainInteractionRangeType.Builder newBuilder() {
    return new com.beligum.blocks.schema.ebucore.v2015.avro.gainInteractionRangeType.Builder();
  }
  
  /** Creates a new gainInteractionRangeType RecordBuilder by copying an existing Builder */
  public static com.beligum.blocks.schema.ebucore.v2015.avro.gainInteractionRangeType.Builder newBuilder(com.beligum.blocks.schema.ebucore.v2015.avro.gainInteractionRangeType.Builder other) {
    return new com.beligum.blocks.schema.ebucore.v2015.avro.gainInteractionRangeType.Builder(other);
  }
  
  /** Creates a new gainInteractionRangeType RecordBuilder by copying an existing gainInteractionRangeType instance */
  public static com.beligum.blocks.schema.ebucore.v2015.avro.gainInteractionRangeType.Builder newBuilder(com.beligum.blocks.schema.ebucore.v2015.avro.gainInteractionRangeType other) {
    return new com.beligum.blocks.schema.ebucore.v2015.avro.gainInteractionRangeType.Builder(other);
  }
  
  /**
   * RecordBuilder for gainInteractionRangeType instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<gainInteractionRangeType>
    implements org.apache.avro.data.RecordBuilder<gainInteractionRangeType> {

    private java.lang.CharSequence bound;

    /** Creates a new Builder */
    private Builder() {
      super(com.beligum.blocks.schema.ebucore.v2015.avro.gainInteractionRangeType.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.beligum.blocks.schema.ebucore.v2015.avro.gainInteractionRangeType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bound)) {
        this.bound = data().deepCopy(fields()[0].schema(), other.bound);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing gainInteractionRangeType instance */
    private Builder(com.beligum.blocks.schema.ebucore.v2015.avro.gainInteractionRangeType other) {
            super(com.beligum.blocks.schema.ebucore.v2015.avro.gainInteractionRangeType.SCHEMA$);
      if (isValidValue(fields()[0], other.bound)) {
        this.bound = data().deepCopy(fields()[0].schema(), other.bound);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'bound' field */
    public java.lang.CharSequence getBound() {
      return bound;
    }
    
    /** Sets the value of the 'bound' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.gainInteractionRangeType.Builder setBound(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.bound = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'bound' field has been set */
    public boolean hasBound() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'bound' field */
    public com.beligum.blocks.schema.ebucore.v2015.avro.gainInteractionRangeType.Builder clearBound() {
      bound = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public gainInteractionRangeType build() {
      try {
        gainInteractionRangeType record = new gainInteractionRangeType();
        record.bound = fieldSetFlags()[0] ? this.bound : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
