//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.14 at 11:54:25 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://purl.org/dc/elements/1.1/")
package com.beligum.blocks.schema.dublincore.v2002;
