//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.19 at 12:10:19 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ebu:metadata-schema:ebuCore_2015", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
    @javax.xml.bind.annotation.XmlNs(namespaceURI = "urn:ebu:metadata-schema:ebuCore_2015", prefix = "ebucore")
})
package com.beligum.blocks.schema.ebucore.v1_6.jaxb;
